/** 画面に出す文字列（tech-spec §9.4）。コンポーネントに文字列リテラルを直接書かない */
export const strings = {
  attribution: {
    text: '地図・標高データ：国土地理院',
    url: 'https://maps.gsi.go.jp/development/ichiran.html',
  },
  map: {
    ariaLabel: '地図',
    basemap: '背景地図',
    basemaps: { std: '標準', pale: '淡色', photo: '写真' },
    theme: '画面の配色',
    themes: { light: 'ライト', dark: 'ダーク', system: '端末に合わせる' },
  },
  unsupported: {
    title: 'このブラウザには対応していません',
    body: 'raintrace には WebGL 2 と OffscreenCanvas が必要です。Chrome、Edge、Firefox、Safari の最新版でお試しください。',
    missing: {
      webgl2: 'WebGL 2 が使えません',
      offscreenCanvas: 'OffscreenCanvas が使えません',
    },
  },
  dem: {
    dem1a: 'DEM1A',
    dem5a: 'DEM5A',
    dem5b: 'DEM5B',
    dem5c: 'DEM5C',
    dem10b: 'DEM10B',
    /** 主の DEM に、ほかを「一部」として添える（formatDemLabel） */
    withPartial: (main: string, others: readonly string[]) =>
      `${main}（一部 ${others.join('、')}）`,
    // base-spec §40 の DEM1A が無い場合の注意文（base-spec の例は英語。画面は日本語のみ。tech-spec §9.4）
    notDem1aNote:
      'この地域には 1m の DEM が無いため、細かな地形のシミュレーションには限界があります。',
  },
  panel: {
    title: '地点と地形',
    notSelected: '地図をクリックして地点を選んでください',
    point: '地点',
    range: '範囲',
    rangeValue: (sizeM: number) => `${sizeM} m 四方`,
    dem: '使った DEM',
    cellSize: 'セルの大きさ',
    invalidRatio: '無効セル',
    elevation: '標高',
    elevationMin: '最低',
    elevationMax: '最高',
    cursor: 'カーソル位置の標高',
    cursorOutside: '範囲外',
    cursorNoData: 'データなし',
    depressions: '窪地',
    depressionCount: '表示対象',
    depressionCountUnit: '件',
    largest: '容量が最大の窪地',
    maxDepth: '最大深さ',
    capacity: '容量',
    spillElevation: 'spill 標高',
    display: '表示',
    showElevation: '標高',
    showDepressions: '窪地（満水時の深さ）',
    showFlow: '地形の流向',
    flowSpacing: '矢印の間隔',
    flowSpacingValue: (spacingM: number) => `${spacingM} m`,
    loading: '標高データを読み込んでいます',
    retry: '再試行',
    showWaterFlow: '水の流れ',
    showOutflow: '流出しているセル',
    terrain: '地形',
    collapse: 'たたむ',
    expand: '開く',
  },
  rainfall: {
    title: '降雨',
    intensity: '時間雨量（mm/h）',
    intensitySlider: '時間雨量のスライダー',
    intensityError: '1〜300 の整数で入力してください',
    duration: '継続時間',
    /** 継続時間の選択肢（spec 08 §4.1）: 60 分未満は「N 分」、以上は「N 時間」 */
    durationValue: (minutes: number) => (minutes < 60 ? `${minutes} 分` : `${minutes / 60} 時間`),
    wholeRange: '範囲全体に降らせる',
    radius: '半径（m）',
    radiusSlider: '半径のスライダー',
    radiusError: (maxM: number) => `1〜${maxM} m の範囲で入力してください`,
    rangeSize: '範囲の大きさ',
    rangeSizeValue: (sizeM: number) => `${sizeM} m`,
    // 1000 m は計算に時間がかかる（tech-spec §14.1、spec 08 §7.2）。ユーザー裁定（2026-09-18、M6）: 選択肢は残し、注意書きを出す
    rangeSizeHeavyHint:
      '範囲 1000 m は計算に時間がかかることがあります（雨を範囲全体に降らせると特に）。',
  },
  playback: {
    title: '再生',
    start: '開始',
    pause: '一時停止',
    resume: '再開',
    step: '1 step 進める',
    reset: 'リセット',
    speed: '速度',
    /** 実時間の倍率（spec 08 §6.2）。1 は「実時間」 */
    speedValue: (speed: number) => (speed === 1 ? '実時間' : `${speed} 倍`),
    max: '最速',
    /** 自動停止（spec 08 §3.9・§6.2）。settled は水の動きが止まったとき、cap は雨の後の上限で止めたとき */
    settled: (elapsed: string) => `水の動きがほぼ止まりました（経過 ${elapsed}）`,
    // 「6 時間」は SETTLE_CAP_S（src/simulation/constants.ts）。ui は simulation の値を import しないので文で持つ
    cap: (elapsed: string) => `計算の上限（雨がやんでから 6 時間）に達しました（経過 ${elapsed}）`,
    reload: '再読み込み',
  },
  simErrors: {
    'no-elevation-at-rain-center': '降雨中心に標高データがありません',
    internal: '計算中にエラーが起きました',
    worker: '計算用の Worker が停止しました。再読み込みすると範囲を読み込み直します',
  },
  stats: {
    title: '統計',
    elapsed: '経過時間',
    rain: '降雨',
    rainDepth: '累積雨量',
    step: 'Step',
    total: '投入水量',
    stored: '領域内の水量',
    outflow: '領域外流出量',
    outflowHelpLabel: '領域外流出量の説明',
    outflowHelp:
      '範囲の端や、海などの標高データの無い場所から、外へ流れ出た水の量です。「領域外流出量」は開始からの合計、「流出の速さ」はその時点の 1 時間あたりの量です。下水道・地面への浸み込み・蒸発は考えていません。',
    outflowRate: '流出の速さ',
    maxDepth: '最大水深',
    floodedArea: '湛水面積',
    speed: '実行速度',
    raining: (remaining: string) => `降雨中（残り ${remaining}）`,
    rainEnded: '降雨終了',
    playbackRate: (ratio: string, stepsPerSecond: string) =>
      `実時間の ${ratio} 倍（${stepsPerSecond}）`,
  },
  spill: {
    title: '越流',
    started: (spillElevation: string, elapsed: string) =>
      `窪地（spill 標高 ${spillElevation}）から越流が始まりました（経過 ${elapsed}）`,
  },
  display: {
    waterPalette: '水深の配色',
    stepped: '5 cm 刻み',
    continuous: '連続',
  },
  view3d: {
    mode: '表示の方式',
    view2d: '2D',
    view3d: '3D',
    exaggeration: '垂直強調',
    exaggerationValue: (value: number) => `${value}x`,
    loading: '3D の表示を準備しています',
    error: '3D の表示を始められませんでした。2D の表示は使えます',
    fallback: 'ズームが粗いため 2D で表示しています。近づくと 3D になります',
  },
  legend: {
    /** 見出し。palette は waterStepped・waterContinuous */
    waterTitle: (palette: string) => `水深（${palette}）`,
    waterStepped: '5 cm 刻み',
    waterContinuous: '連続',
    waterMin: '0.01 m',
    waterMid: '0.5 m',
    waterMax: '1 m 以上',
    waterAria: '水深の凡例。1 cm 未満は表示しない。浅いほど明るい青、1 m 以上は最も濃い青',
    waterThinNote: '1 cm 未満の薄い水は表示しません（領域内の水量には含みます）。',
    depression: '窪地（満水時の深さ）',
    depressionMin: '0 m',
    depressionMax: '0.35 m 以上',
    depressionAria: '窪地の凡例。5 cm 刻みの 8 段で、深いほど濃い赤紫',
    markersAria: '地図の印の凡例。青い丸は最低点、オレンジの丸はあふれ出し点',
    outflow: 'この辺りから範囲の外へ流出中',
    outflowAria: '流出の凡例。濃いピンクの帯は、この辺りから範囲の外へ水が流れ出ていることを示す',
  },
  cellInfo: {
    elevation: '標高',
    depth: '水深',
    level: '水位',
    noData: '標高データなし',
    useAsCenter: 'ここを降雨中心にする',
    newPoint: 'ここを新しい地点にする',
    close: '閉じる',
  },
  /** 地図の ○ の説明（spec 07 §3.4） */
  markerInfo: {
    lowest: {
      title: '最低点',
      body: '範囲の中でいちばん低い地点です。水が集まりやすい場所の目安です。',
    },
    spill: {
      title: 'あふれ出し点',
      body: 'くぼ地が水で満たされると、ここから水があふれ出します。',
    },
    elevation: '標高',
    spillElevation: 'あふれる標高',
    maxDepth: 'くぼ地の最大の深さ',
    capacity: 'ためられる水の量',
    area: 'くぼ地の面積',
    close: '閉じる',
  },
  /** 数値の単位と組み立て（src/ui/format.ts が使う。桁の丸めは format.ts が行い、ここは文字列だけ） */
  format: {
    meters: (value: string) => `${value} m`,
    cellSize: (value: string) => `約 ${value} m`,
    percent: (value: string) => `${value}%`,
    cubicMeters: (value: string) => `${value} m³`,
    area: (value: string) => `${value} m²`,
    stepsPerSecond: (value: string) => `${value} step/秒`,
    step: (step: number) => `Step ${step}`,
    hoursMinutes: (hours: number, minutes: number) => `${hours}時間${minutes}分`,
    minutesSeconds: (minutes: number, seconds: number) => `${minutes}分${seconds}秒`,
    seconds: (seconds: number) => `${seconds}秒`,
    rainDepth: (fallen: number, total: number) => `${fallen} mm / ${total} mm`,
    cubicMetersPerHour: (value: string) => `${value} m³/時`,
    none: '—',
  },
  errors: {
    'no-data': 'この地域には標高データがありません',
    network: '標高データを取得できませんでした',
    internal: '標高データの処理中にエラーが起きました',
    worker: '計算用の Worker が停止しました。再試行すると起動し直します',
    'out-of-range': 'この地点は対応範囲（日本国内）の外です',
  },
  disclaimer: {
    title: '注意事項',
    lines: [
      '本シミュレーションは地形標高データを用いた簡易モデルです。',
      '実際の浸水・洪水・災害を予測するものではありません。',
      '建物、道路構造、下水道、河川流量、排水設備等は考慮されていません。',
      '範囲の端や標高データの無い場所に達した水は、範囲の外へ流れ出たものとして扱います。',
    ],
    acknowledge: '了解しました',
    close: '閉じる',
    notice: '簡易モデルによる参考表示です。実際の浸水・災害を予測するものではありません。',
    showFull: '注意事項の全文',
    author: '作成者: @terapyon',
    sourceCode: {
      label: 'ソースコード: ',
      linkText: 'GitHub（terapyon/raintrace）',
      url: 'https://github.com/terapyon/raintrace',
    },
  },
} as const
