/** 画面に出す文字列（tech-spec §9.4）。コンポーネントに文字列リテラルを直接書かない */
export const strings = {
  attribution: {
    text: '地図・標高データ：国土地理院',
    url: 'https://maps.gsi.go.jp/development/ichiran.html',
  },
  map: {
    ariaLabel: '地図',
  },
  unsupported: {
    title: 'このブラウザには対応していません',
    body: 'raintrace には WebGL 2 と OffscreenCanvas が必要です。Chrome、Edge、Firefox、Safari の最新版でお試しください。',
    missing: {
      webgl2: 'WebGL 2 が使えません',
      offscreenCanvas: 'OffscreenCanvas が使えません',
    },
  },
  dem: {
    dem1a: 'DEM1A',
    dem5a: 'DEM5A',
    dem5b: 'DEM5B',
    dem5c: 'DEM5C',
    dem10b: 'DEM10B',
    partial: '一部',
    // base-spec §40 の DEM1A が無い場合の注意文（base-spec の例は英語。画面は日本語のみ。tech-spec §9.4）
    notDem1aNote:
      'この地域には 1m の DEM が無いため、細かな地形のシミュレーションには限界があります。',
  },
  panel: {
    title: '地点と地形',
    notSelected: '地図をクリックして地点を選んでください',
    point: '地点',
    range: '範囲',
    rangeValue: (sizeM: number) => `${sizeM} m 四方`,
    dem: '使った DEM',
    cellSize: 'セルの大きさ',
    invalidRatio: '無効セル',
    elevation: '標高',
    elevationMin: '最低',
    elevationMax: '最高',
    cursor: 'カーソル位置の標高',
    cursorOutside: '範囲外',
    cursorNoData: 'データなし',
    depressions: '窪地',
    depressionCount: '表示対象',
    depressionCountUnit: '件',
    largest: '容量が最大の窪地',
    maxDepth: '最大深さ',
    capacity: '容量',
    spillElevation: 'spill 標高',
    display: '表示',
    showElevation: '標高',
    showDepressions: '窪地（満水時の深さ）',
    showFlow: '地形の流向',
    flowSpacing: '矢印の間隔',
    loading: '標高データを読み込んでいます',
    retry: '再試行',
  },
  legend: {
    water: '水深',
    waterStepped: '5 cm 刻み',
    waterContinuous: '連続',
    waterMin: '0.01 m',
    waterMid: '0.5 m',
    waterMax: '1 m 以上',
    waterAria: '水深の凡例。1 cm 未満は表示しない。浅いほど明るい青、1 m 以上は最も濃い青',
    depression: '窪地（満水時の深さ）',
    depressionMin: '0 m',
    depressionMax: '0.35 m 以上',
    depressionAria: '窪地の凡例。5 cm 刻みの 8 段で、深いほど濃い赤紫',
  },
  errors: {
    'no-data': 'この地域には標高データがありません',
    network: '標高データを取得できませんでした',
    internal: '標高データの処理中にエラーが起きました',
    worker: '計算用の Worker が停止しました。再試行すると起動し直します',
    'out-of-range': 'この地点は対応範囲（日本国内）の外です',
  },
} as const
