/** 画面に出す文字列（tech-spec §9.4）。コンポーネントに文字列リテラルを直接書かない */
export const strings = {
  attribution: {
    text: '地図・標高データ：国土地理院',
    url: 'https://maps.gsi.go.jp/development/ichiran.html',
  },
  map: {
    ariaLabel: '地図',
    basemap: '背景地図',
    basemaps: { std: '標準', pale: '淡色', photo: '写真' },
    theme: '画面の配色',
    themes: { light: 'ライト', dark: 'ダーク', system: '端末に合わせる' },
  },
  unsupported: {
    title: 'このブラウザには対応していません',
    body: 'raintrace には WebGL 2 と OffscreenCanvas が必要です。Chrome、Edge、Firefox、Safari の最新版でお試しください。',
    missing: {
      webgl2: 'WebGL 2 が使えません',
      offscreenCanvas: 'OffscreenCanvas が使えません',
    },
  },
  dem: {
    dem1a: 'DEM1A',
    dem5a: 'DEM5A',
    dem5b: 'DEM5B',
    dem5c: 'DEM5C',
    dem10b: 'DEM10B',
    /** 主の DEM に、ほかを「一部」として添える（formatDemLabel） */
    withPartial: (main: string, others: readonly string[]) =>
      `${main}（一部 ${others.join('、')}）`,
    // base-spec §40 の DEM1A が無い場合の注意文（base-spec の例は英語。画面は日本語のみ。tech-spec §9.4）
    notDem1aNote:
      'この地域には 1m の DEM が無いため、細かな地形のシミュレーションには限界があります。',
  },
  panel: {
    title: '地点と地形',
    notSelected: '地図をクリックして地点を選んでください',
    point: '地点',
    range: '範囲',
    rangeValue: (sizeM: number) => `${sizeM} m 四方`,
    dem: '使った DEM',
    cellSize: 'セルの大きさ',
    invalidRatio: '無効セル',
    elevation: '標高',
    elevationMin: '最低',
    elevationMax: '最高',
    cursor: 'カーソル位置の標高',
    cursorOutside: '範囲外',
    cursorNoData: 'データなし',
    depressions: '窪地',
    depressionCount: '表示対象',
    depressionCountUnit: '件',
    largest: '容量が最大の窪地',
    maxDepth: '最大深さ',
    capacity: '容量',
    spillElevation: 'spill 標高',
    display: '表示',
    showElevation: '標高',
    showDepressions: '窪地（満水時の深さ）',
    showFlow: '地形の流向',
    flowSpacing: '矢印の間隔',
    flowSpacingValue: (spacingM: number) => `${spacingM} m`,
    loading: '標高データを読み込んでいます',
    retry: '再試行',
    showWaterFlow: '水の流れ',
    terrain: '地形',
    collapse: 'たたむ',
    expand: '開く',
  },
  rainfall: {
    title: '降雨',
    amount: '雨量（mm）',
    amountSlider: '雨量のスライダー',
    radius: '半径（m）',
    radiusSlider: '半径のスライダー',
    amountError: '1〜1000 の整数で入力してください',
    radiusError: (maxM: number) => `1〜${maxM} m の範囲で入力してください`,
    rangeSize: '範囲の大きさ',
    rangeSizeValue: (sizeM: number) => `${sizeM} m`,
  },
  playback: {
    title: '再生',
    start: '開始',
    pause: '一時停止',
    resume: '再開',
    step: '1 step 進める',
    reset: 'リセット',
    speed: '速度',
    speedValue: (speed: number) => `${speed}x`,
    max: '最速',
    settled: (step: number) => `平衡に達しました（Step ${step}）`,
    reload: '再読み込み',
  },
  simErrors: {
    'no-elevation-at-rain-center': '降雨中心に標高データがありません',
    internal: '計算中にエラーが起きました',
    worker: '計算用の Worker が停止しました。再読み込みすると範囲を読み込み直します',
  },
  stats: {
    title: '統計',
    step: 'Step',
    total: '投入水量',
    stored: '領域内の水量',
    outflow: '領域外流出量',
    maxDepth: '最大水深',
    floodedArea: '湛水面積',
    speed: '実行速度',
  },
  spill: {
    title: '越流',
    started: (spillElevation: string, step: number) =>
      `窪地（spill 標高 ${spillElevation}）から越流が始まりました（Step ${step}）`,
  },
  display: {
    waterPalette: '水深の配色',
    stepped: '5 cm 刻み',
    continuous: '連続',
  },
  view3d: {
    mode: '表示の方式',
    view2d: '2D',
    view3d: '3D',
    exaggeration: '垂直強調',
    exaggerationValue: (value: number) => `${value}x`,
    loading: '3D の表示を準備しています',
    error: '3D の表示を始められませんでした。2D の表示は使えます',
    fallback: 'ズームが粗いため 2D で表示しています。近づくと 3D になります',
  },
  legend: {
    /** 見出し。palette は waterStepped・waterContinuous */
    waterTitle: (palette: string) => `水深（${palette}）`,
    waterStepped: '5 cm 刻み',
    waterContinuous: '連続',
    waterMin: '0.01 m',
    waterMid: '0.5 m',
    waterMax: '1 m 以上',
    waterAria: '水深の凡例。1 cm 未満は表示しない。浅いほど明るい青、1 m 以上は最も濃い青',
    depression: '窪地（満水時の深さ）',
    depressionMin: '0 m',
    depressionMax: '0.35 m 以上',
    depressionAria: '窪地の凡例。5 cm 刻みの 8 段で、深いほど濃い赤紫',
  },
  cellInfo: {
    elevation: '標高',
    depth: '水深',
    level: '水位',
    noData: '標高データなし',
    useAsCenter: 'ここを降雨中心にする',
    newPoint: 'ここを新しい地点にする',
    close: '閉じる',
  },
  /** 数値の単位と組み立て（src/ui/format.ts が使う。桁の丸めは format.ts が行い、ここは文字列だけ） */
  format: {
    meters: (value: string) => `${value} m`,
    cellSize: (value: string) => `約 ${value} m`,
    percent: (value: string) => `${value}%`,
    cubicMeters: (value: string) => `${value} m³`,
    area: (value: string) => `${value} m²`,
    stepsPerSecond: (value: string) => `${value} step/秒`,
    step: (step: number) => `Step ${step}`,
    none: '—',
  },
  errors: {
    'no-data': 'この地域には標高データがありません',
    network: '標高データを取得できませんでした',
    internal: '標高データの処理中にエラーが起きました',
    worker: '計算用の Worker が停止しました。再試行すると起動し直します',
    'out-of-range': 'この地点は対応範囲（日本国内）の外です',
  },
  disclaimer: {
    title: '注意事項',
    lines: [
      '本シミュレーションは地形標高データを用いた簡易モデルです。',
      '実際の浸水・洪水・災害を予測するものではありません。',
      '建物、道路構造、下水道、河川流量、排水設備等は考慮されていません。',
    ],
    acknowledge: '了解しました',
    close: '閉じる',
    notice: '簡易モデルによる参考表示です。実際の浸水・災害を予測するものではありません。',
    showFull: '注意事項の全文',
  },
} as const
